### PR TITLE
Update planet parameters

### LINKED ISSUE #442: Update planet parameters
The new planet (HD 145934 b) has already been added.

http://arxiv.org/abs/1501.00633

### PR DESCRIPTION
**Pull request by Nexusty**
closes #442
Updated planet parameters and created new system GJ 849.
source: http://arxiv.org/abs/1501.00633

### CODE REVIEW

**Comment by Sol-d** [comment]
You added  GJ 849.xml. I found, that Gliese 849. xml is already listed, since OEC uses the notation "Gliese xxxx.xml". I think you should update the already existing file.

**Comment by ajtribick** [comment]
What's the plan with this one - is it possible to use this pull request and then merge the two Gliese 849 files?

**Comment by hannorein** [comment]
I think @Nexusty was going to work on it. Not sure when though. If anyone else want to use the data in this pull request, you can merge @Nexusty's branch into your repository and then open a new pull request from your repository to the main repository.

**Comment by ajtribick** [comment]
These changes were done in pull request #664, this one can be closed

**Pull request closed without merging**
