### PR TITLE
Add Proxima b

### LINKED ISSUE #943: Proxima b
Add the new neighbour! http://www.eso.org/public/news/eso1629/

### PR DESCRIPTION
**Pull request by ajtribick**
Closes #943

Planet and stellar parameters
Anglada-Escudé et al. (2016) http://cdsads.u-strasbg.fr/abs/2016Natur.536..437A

Parallax
Lurie et al. (2014) http://cdsads.u-strasbg.fr/abs/2014AJ....148...91L

Coordinates, magnitudes and additional identifiers from SIMBAD

### CODE REVIEW

**Comment by hannorein** [comment]
Proxima is already in the catalogue. It's part of the Alpha Centauri system. Are there new parameters in this PR that are on in the Alpha Cen file yet?

**Comment by ajtribick** [comment]
The Alpha Centauri file only contains the A and B stars. Since both [Wertheimer & Laughlin (2006)](http://cdsads.u-strasbg.fr/abs/2006AJ....132.1995W) and [Matvienko & Orlov (2014)](http://cdsads.u-strasbg.fr/abs/2014AstBu..69..205M) find quite high probabilities that Proxima is not a bound member of Alpha Centauri (and as far as I can see, the question of whether Proxima is part of Alpha Centauri has not been addressed with the latest RV data that was used to discover Proxima b), I put it in a separate file.

**Comment by hannorein** [comment]
You are right, I forgot to push my local changes. Still not sure about the separate file.

**Comment by ajtribick** [comment]
Ok, will close this one for now. It might be worth adding the error bars and the type="msini" to the mass value for Proxima b. Incidentally the mass conversion appears to be off, 1.27 Earth masses = 0.004089 Jupiter masses implies a Jupiter mass of 310.5 Earth masses, the usual values I find are around 317.8.

**Pull request closed without merging**
