### PR TITLE
KOI-368.01 is likely an M-dwarf star.

### PR DESCRIPTION
**Pull request by ajtribick**
Updated description to reflect …more recent alignment value.

Ahlers et al. (2014) http://cdsads.u-strasbg.fr/abs/2014ApJ...786..131A

### CODE REVIEW

**Comment by hannorein** [comment]
Should we move this one from the confirmed planets to the controversial list?

**Comment by ajtribick** [comment]
I think so, yes.

**Comment by ajtribick** [comment]
Updated.

**Comment by ajtribick** [comment]
Is this one ok or are further changes needed?

**Pull request merged**
