### PR TITLE
Kepler clean-up/update

### PR DESCRIPTION
**Pull request by ajtribick**
Semi-automated cleanup of Kepler/KOI/KIC identifiers using NASA Kepler names table

* Fixed mismatched identifiers
* Added missing Kepler/KOI/KIC identifiers
* Merged duplicate system Kepler-78 = KIC 8345766
* Added missing Kepler planets

### CODE REVIEW

**Comment by ajtribick** [comment]
NB the Kepler-419 file uses the meananomaly tag which wasn't present when I originally branched this, so the Travis build may fail on that.

**Comment by hannorein** [comment]
Wow. This pull request is a really big. I'm having a hard time figuring out what's going on. And I'm a little worried that it messes up some of the names. For example, we were very careful to label planet in exactly the way the discovery paper does. 

Can you split this up into smaller portion that are conceptually similar (i.e. one pull request for a new planet, one for a script that adds other names, etc). 

Also, if you have the script somewhere, maybe you could post a link to it. It might be easier to look at the script to see what it does rather than checking all 447 files.

**Comment by ajtribick** [comment]
The issues with labelling planets in the way the discovery paper does is why this is a semi-automated clean-up: the scripts were used to locate the conflicts/missing designations and then I manually edited them. This was important in order to handle binary star designations and preserve such anomalies as the KOI-314/Kepler-138 planet names - in cases where there were letter mismatches between designations I checked in the source papers for the designations. The exception was the removal of names of the form KIC nnnnn.nn which are not actually in use (601c6e1). If you feel that it is vitally important to retain these odd hybrids of KIC and KOI designations then it would be fairly straightforward to autogenerate them, otherwise reverse the 601c6e1 commit.

Aside from 601c6e1, the other commits each contain a much more "reasonable" number of files changed so it shouldn't be too difficult to go through to find places where things were changed as opposed to addition of new designations.

Kepler-296 I removed the "A" part of the designation as it is not yet clear that the planets orbit the A star. This is actually more consistent with the original form in which the designations were introduced.

A few unconfirmed KOIs I removed letter designations from: if it is important to render designations as the discoverers give them, it is therefore also important not to pre-empt future discoverers by assigning new letters.

Commits 887b355 onwards are data changes to bring the OEC in-line with the confirmed planets list from the Kepler mission, mostly missing planets apart from 887b355 itself which results in the removal of an M-dwarf star from the confirmed list.

**Comment by hannorein** [comment]
Moving the discussion from 3dc6de4ef19450c7068c3959da8048f555c78542 over here.

1) Whether the plus sign is there or not is not the issue. 
2) But we cannot rename, for example, a KOI planet to be a Kepler planet.
3) Given that the pull request has so many changed files, I'm still struggling to see what's going on and thus hesitant to merge.

**Comment by hannorein** [comment]
I'm going to close this one. Please open one separate pull request for each conceptual change. That way we can discuss them individually, but this one is just too convoluted.

**Comment by ajtribick** [comment]
Not sure it makes sense to merge the discussion here, particularly since you were clearly intending to close this as soon as you did that, and the + sign was an example used to illustrate a general issue rather than something related to this pull request specifically. I am in agreement with your point 2 which is why I spent the (apparently wasted) effort doing manual edits.

The split into conceptual changes was why I used several commits rather than just doing it in one go. That also should simplify the task of reviewing it, you can click each one individually rather than trying to do the whole branch at once.

**Comment by hannorein** [comment]
If you open multiple pull requests, I can merge this partially.

**Pull request closed without merging**
