### PR TITLE
added HD 1605, HD 1666, HD 67087

### LINKED ISSUE #532: Add 5 new planets
http://arxiv.org/pdf/1503.07636v1.pdf

### PR DESCRIPTION
**Pull request by Sol-d**
Source
http://arxiv.org/pdf/1503.07636v1.pdf
Positions and fluxes from SIMBAD
closes #532

### CODE REVIEW

**Comment by hannorein** [comment]
These are not transiting planets. Why do they have a transit time tag?

**Comment by Sol-d** [comment]
Yes, they are not transiting, so the transit-tag is wrong.

**Comment by hannorein** [comment]
What do the numbers correspond to?

**Comment by Sol-d** [comment]
The paper names Tc for each planet, table in last page.

**Comment by hannorein** [comment]
Ah, that should probably be `periastrontime`

**Comment by Sol-d** [comment]
Ok, i will make the corrections until friday. Feel free if you want to make the corrections immediately.

**Comment by hannorein** [comment]
No rush!

**Comment by Sol-d** [comment]
will open a new pull request since i don't know how to change the files in this pr

**Comment by hannorein** [comment]
For the future: You can just push new commits to the same branch and then add them to the pull request.

**Pull request closed without merging**
