### PR TITLE
Add K2 Campaign 1 Planets - Part I

### PR DESCRIPTION
**Pull request by Sol-d**
Source
http://arxiv.org/pdf/1503.07866v1
these systems will be added in another pull request since they are still in OEC and have to check: 201367065, 201505350

### CODE REVIEW

**Comment by hannorein** [comment]
We need to change the names. If we use letter identifiers, start at b (A is used for the star). E.g. 

201208431.01-> 201208431 b

Keep the numeric identifiers as a secondary name.

**Comment by Sol-d** [comment]
here it is...

**Comment by hannorein** [comment]
Fantastic. Thanks! (And sorry for the extra work due to the naming issue)

**Comment by Sol-d** [comment]
it was my fault. i know, that the planet designations starts with "b".

**Pull request merged**
