### PR TITLE
Merged duplicate systems KIC 8435766=Kepler-78.

### PR DESCRIPTION
**Pull request by ajtribick**
The KIC 8435766 name has priority so I preserve that path, with the latest data from the Kepler-78 file. Not sure if there is a better way of doing this so it tracks the history better.

### CODE REVIEW

**Comment by ajtribick** [comment]
Check for duplicate designations turned up another duplicate pair: KOI-183 = Kepler-423. Based on the [first version of the arXiv preprint](http://arxiv.org/abs/1409.8245v1) using "KOI-183b", I think KOI-183 should be the primary name. Would you prefer I update this pull request or that I open a new one?

**Comment by hannorein** [comment]
A separate one please. And sorry for being slow with merging these. I just really want to make sure we don't mess up anything. Name changes have proven to be tricky in the past..

**Comment by ajtribick** [comment]
Raised #576 to track this and the KOI-183=Kepler-423 pair

**Comment by ajtribick** [comment]
Any issues with this one, or can it be merged?

**Comment by hannorein** [comment]
Yes. Sorry for the delay.

**Pull request merged**
