### PR TITLE
Update Kepler-338

### PR DESCRIPTION
**Pull request by ajtribick**
Added planet Kepler-338 e
Removed KIC nnnnn.nn designations (not in actual use)

Hadden & Lithwick (2014) http://adsabs.harvard.edu/abs/2014ApJ...787...80H
Additional data from NASA Kepler Objects of Interest cumulative table.
Additional data from NASA confirmed planets overview.

### CODE REVIEW

**Comment by hannorein** [comment]
The general idea is to keep as many identifiers as possible. Including the KIC nnnnnn.nn one. The reason is simply that if someone googles it, the Open Exoplanet Catalogue will show up.

**Comment by ajtribick** [comment]
Not sure why you would expect someone to Google this. Unlike the case of the letter suffixes, there doesn't appear to be much precedent for taking the second part of the KOI identifier and putting it on the end of a different stellar designation.

**Comment by hannorein** [comment]
There is no harm done keeping an additional identifier. Note that the people also sometimes use numerical suffixes for the KOI identifiers.

**Comment by ajtribick** [comment]
Well if you think these are vitally important to keep around, I've re-added the ones that were in the file.

**Pull request merged**
